/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EarnRewardsRouteImport } from './routes/earn-rewards'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRewardsRoute = EarnRewardsRouteImport.update({
  id: '/earn-rewards',
  path: '/earn-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRoute
  '/earn-rewards': typeof EarnRewardsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRoute
  '/earn-rewards': typeof EarnRewardsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/documents': typeof DocumentsRoute
  '/earn-rewards': typeof EarnRewardsRoute
  '/login': typeof LoginRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/documents'
    | '/earn-rewards'
    | '/login'
    | '/performance'
    | '/settings'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/documents'
    | '/earn-rewards'
    | '/login'
    | '/performance'
    | '/settings'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/documents'
    | '/earn-rewards'
    | '/login'
    | '/performance'
    | '/settings'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DocumentsRoute: typeof DocumentsRoute
  EarnRewardsRoute: typeof EarnRewardsRoute
  LoginRoute: typeof LoginRoute
  PerformanceRoute: typeof PerformanceRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn-rewards': {
      id: '/earn-rewards'
      path: '/earn-rewards'
      fullPath: '/earn-rewards'
      preLoaderRoute: typeof EarnRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DocumentsRoute: DocumentsRoute,
  EarnRewardsRoute: EarnRewardsRoute,
  LoginRoute: LoginRoute,
  PerformanceRoute: PerformanceRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
